# Generated by Django 3.0.2 on 2020-02-14 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('campus', models.IntegerField(blank=True, choices=[(0, 'Goa'), (1, 'Hyderabad'), (2, 'Pilani')], null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('user_type', models.IntegerField(blank=True, choices=[(0, 'Student'), (1, 'Supervisor'), (2, 'Head of Department'), (3, 'Associate Dean'), (4, 'PS-Division')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PS2TSTransfer',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transfers.UserProfile')),
                ('supervisor_email', models.EmailField(max_length=254)),
                ('hod_email', models.EmailField(max_length=254)),
                ('sub_type', models.IntegerField(choices=[(0, 'PS to TS (Single Degree)'), (1, 'PS-TS/TS-PS to TS-TS (Dual Degree)')])),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('thesis_locale', models.IntegerField(choices=[(0, 'On Campus'), (1, 'Off Campus (India)'), (2, 'Off Campus Abroad')])),
                ('thesis_subject', models.CharField(help_text='Broad area/Title of Thesis', max_length=150)),
                ('name_of_org', models.CharField(help_text='Name of BITS Campus or Organization where thesis will be carried', max_length=100)),
                ('expected_deliverables', models.TextField(help_text='Expected outcome of thesis')),
                ('is_supervisor_approved', models.BooleanField(default=False)),
                ('is_hod_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PS to TS Application',
                'verbose_name_plural': 'PS to TS Applications',
            },
        ),
        migrations.CreateModel(
            name='TS2PSTransfer',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transfers.UserProfile')),
                ('hod_email', models.EmailField(max_length=254)),
                ('sub_type', models.IntegerField(choices=[(0, 'TS to PS (Single Degree)'), (1, 'PS-TS to PS-PS (Dual Degree)'), (2, 'TS-TS to TS-PS (Dual Degree)')])),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason_for_transfer', models.TextField()),
                ('name_of_org', models.CharField(help_text='Name of BITS Campus or Organization where thesis was being carried', max_length=100)),
                ('is_hod_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'TS to PS Application',
                'verbose_name_plural': 'TS to PS Applications',
            },
        ),
    ]
