# Generated by Django 3.0.2 on 2020-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ps2tstransfer',
            name='is_ad_approved',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='ts2pstransfer',
            name='is_ad_approved',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
