# Generated by Django 3.0.3 on 2020-02-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ts2pstransfer',
            old_name='reson_for_transfer',
            new_name='reason_for_transfer',
        ),
    ]
