# Generated by Django 3.0.2 on 2020-04-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_add_is_ad_approved_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, help_text='Enter 10 digit contact number', max_length=10, null=True),
        ),
    ]
