# Generated by Django 3.0.4 on 2020-04-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_change_contact_field_to_CharField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, help_text='Enter 10 digit contact number', max_length=20, null=True),
        ),
    ]
